### ISSUE TITLE
Load预训练参数后发现效果不太对

### ISSUE THREAD

**Issue by CoderAnn** [shibing624/lmft#10]
![image](https://user-images.githubusercontent.com/37071625/230821782-28892e39-ea1b-43b9-a058-de4a92fe60dc.png)

没有修改代码，Load预训练好的Lora参数后推理发现模型效果不一致。
请问是为什么呢？

**Comment by shibing624** [comment]
下载最新的chatglm-6b 权重（官方权重最近一周更新频繁），再试试，我本地测试ok的。   https://huggingface.co/THUDM/chatglm-6b/tree/main
