### ISSUE TITLE
触发到训练后的数据时，回答完成后会继续产生超长的不相关内容

### ISSUE THREAD

**Issue by xioozq** [shibing624/lmft#14]
如图：在前两轮没有触发到lora数据时回复正常，
但是第三句触发到了lora训练数据后，在回答完成后还产生了大量不相关内容。

![QQ截图20230411010413](https://user-images.githubusercontent.com/24352342/230953165-f48a11ab-6ddf-4252-8b85-4e8cf477a9b2.png)

使用的是官方的cli_demo加了peft 挂载， 
````python
import os
import platform
import signal
from transformers import AutoTokenizer, AutoModel
from peft import PeftModel

lora_path = '/root/autodl-tmp/train/ad'

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)

if lora_path:
    model = PeftModel.from_pretrained(model, lora_path)
    print('use lora.')
model = model.half().cuda()
model = model.eval()
````
lora模型的adapter_config.json如下：
````json
{
  "base_model_name_or_path": "THUDM/chatglm-6b",
  "bias": "none",
  "enable_lora": [
    true,
    false,
    true
  ],
  "fan_in_fan_out": true,
  "inference_mode": false,
  "lora_alpha": 32,
  "lora_dropout": 0.1,
  "merge_weights": false,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 8,
  "target_modules": [
    "query_key_value"
  ],
  "task_type": "CAUSAL_LM"
}
````

**Comment by shibing624** [comment]
update eos token: https://huggingface.co/THUDM/chatglm-6b/commit/aa51e62ddc9c9f334858b0af44cf59b05c70148a   更新权重文件的：
wget https://huggingface.co/THUDM/chatglm-6b/resolve/main/tokenization_chatglm.py
wget https://huggingface.co/THUDM/chatglm-6b/resolve/main/modeling_chatglm.py
wget https://huggingface.co/THUDM/chatglm-6b/resolve/main/tokenizer_config.json

**Comment by xioozq** [comment]
更新ChatGLM-6B后解决！

**Comment by xioozq** [comment]
更新ChatGLM-6B后解决！
