### ISSUE TITLE
RuntimeError: The size of tensor a (72) must match the size of tensor b (44) at non-singleton dimension 0

### ISSUE THREAD

**Issue by archwolf118** [shibing624/lmft#8]
您好，在执行
```
cd examples
python training_chatglm_demo.py --do_train
```
时出现RuntimeError: The size of tensor a (72) must match the size of tensor b (44) at non-singleton dimension 0这样的报错。
有解决办法吗？谢谢！

**Comment by shibing624** [comment]
下载最新的chatglm-6b权重 https://huggingface.co/THUDM/chatglm-6b 和lmft代码是可以跑通的。

**Comment by archwolf118** [comment]
好的，谢谢！已经可以跑了。
但是模型微调后，问其他问题会出现生成重复或者无关答案的情况，这样导致预测时间大大增加，我看网上也有很多人遇到这个问题。请问根据您的经验，如何规避该问题？谢谢！

**Comment by archwolf118** [comment]
谢谢！能跑。另外由于新的chatglm-6模型权重更新了，能否根据新的模型权重适配一下。我训练的模型在训练集上表现还可以，但是模型对一般问题的预测会出现超长并且无关的输出，初步判断可能和eos_token_id变化有关,原来模型的eos_token_id为20002，现在最新的模型权重变成2了。
谢谢了！

**Comment by shibing624** [comment]
嗯，chatglm6b 缩减了2000个token，所以词表长度更新了。

**Comment by archwolf118** [comment]
@shibing624 我把训练里面的eos_token都改了130005,结果就好了，这样做到了base模型和lora模型的一致。

**Comment by xioozq** [comment]
> @shibing624 我把训练里面的eos_token都改了130005,结果就好了，这样做到了base模型和lora模型的一致。

我也遇到了输出了多余无关内容的问题，请问是改的哪里？

**Comment by shibing624** [comment]
官方修复了：https://huggingface.co/THUDM/chatglm-6b/commit/aa51e62ddc9c9f334858b0af44cf59b05c70148a

**Comment by shibing624** [comment]
pytorch_model0 和 最后一个也要更新

**Comment by archwolf118** [comment]
上面的问题不存在了，chatglm-6b更新后，修复了eos_token_id的问题
